version: "2"

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
  exclusions:
    paths:
      - cmd/maddy-pam-helper

formatters:
  enable:
    - gofmt
  exclusions:
    paths:
      - cmd/maddy-pam-helper
      - _test.go

run:
  timeout: 5m
